import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { motion } from 'motion/react';
import { ArrowLeft, CheckCircle2, ShieldCheck, Sparkles, Info, Shield, Scale, AlertTriangle, Lock, Ban, Code2 } from 'lucide-react';
import { AestificLogo } from './AestificLogo';
import { DocumentsView, DocTab, DOC_ITEMS } from './DocumentsView';

export const AESTIFIC_TERMS_AND_CONDITIONS = `# Terms of Service & User Agreement

**Last Updated:** September 2026  
**Effective Date:** Immediately upon acceptance

Welcome to **Aestific AI** ("Aestific", "we", "us", or "our"). By accessing or using our artificial intelligence assistant platform, web interfaces, APIs, and associated services (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.

---

## 1. Acceptance of Terms

By creating an account, accessing, or using Aestific AI, you confirm that:
- You are at least 13 years of age (or the legal age of majority in your jurisdiction).
- You possess the legal capacity to enter into a binding agreement.
- You agree to comply with all applicable local, national, and international laws and regulations.
- You accept these Terms and our Privacy Policy in their entirety.

---

## 2. Description of the Service

Aestific AI provides a next-generation minimal AI workspace powered by neural intelligence, featuring:
- Conversational artificial intelligence reasoning and multi-turn dialogue.
- Account-level persistent memory and user personalization.
- Multimodal file comprehension (including documents, PDFs, and code).
- Generative AI image synthesis and prompt enrichment.
- High-fidelity voice transcription and audio interaction.

We continuously improve and evolve the Service. Features, model architectures, and interfaces may be modified, updated, or temporarily suspended without prior notice.

---

## 3. User Accounts & Security

- **Account Confidentiality:** You are responsible for safeguarding your credentials, passwords, and authentication tokens.
- **Account Activity:** You are solely responsible for all activities occurring under your account credentials.
- **Unauthorized Access:** You agree to notify Aestific immediately of any unauthorized use or security breaches.
- **Accuracy:** You agree to provide true, accurate, and current information when registering an account.

---

## 4. Acceptable Use & Conduct

You agree not to use the Service to:
- Generate, transmit, or promote illegal, harmful, threatening, abusive, harassing, defamatory, or hateful content.
- Violate any intellectual property, privacy, or proprietary rights of third parties.
- Generate malware, viruses, exploits, or engage in automated denial-of-service or security penetration attempts.
- Attempt to reverse engineer, decompile, or extract the underlying model weights or proprietary systems.
- Bypass rate limits, quota controls, or platform security safeguards.
- Misrepresent AI-generated outputs as human-authored works in sensitive or regulated domains without proper disclosure.

---

## 5. AI Outputs & Disclaimers

- **Nature of AI:** Artificial intelligence models generate predictions and text based on probabilistic patterns. Outputs may occasionally be inaccurate, incomplete, or biased.
- **Verification Required:** You must independently verify critical information, including legal, medical, financial, tax, or life-safety matters before taking action based on AI output.
- **No Professional Advice:** The Service does not provide professional medical, legal, or financial counseling.
- **Assumption of Risk:** Your reliance on any output generated by Aestific AI is solely at your own risk.

---

## 6. Intellectual Property & User Content

- **Your Inputs:** You retain ownership of any prompts, files, code, and content you submit to the Service ("User Content").
- **Generated Outputs:** To the extent permitted by applicable law, you own the outputs generated specifically for you by the Service, subject to your compliance with these Terms.
- **Service IP:** All brand marks, trade secrets, software code, UI designs, and visual assets associated with Aestific are the exclusive property of Aestific.

---

## 7. Privacy & Data Storage

- We handle personal data in accordance with our Privacy Standards.
- Chat histories and attachments are stored securely within your workspace vault.
- Account controls allow users to clear conversation history, export local data, or delete their account.

---

## 8. Limitation of Liability

To the fullest extent permitted by applicable law:
- The Service is provided on an **"AS IS"** and **"AS AVAILABLE"** basis without warranties of any kind, whether express, implied, or statutory.
- In no event shall Aestific, its affiliates, or licensors be liable for indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, goodwill, or business interruption.

---

## 9. Contact & Support

If you have questions, feedback, or concerns regarding these Terms, you can submit an inquiry directly via the **Support Center** within your Aestific workspace.
`;

interface TermsPageProps {
  onBack: () => void;
  onAccept?: () => void;
  isAccepted?: boolean;
  initialDoc?: DocTab | null;
}

export const TermsPage: React.FC<TermsPageProps> = ({
  onBack,
  onAccept,
  isAccepted = false,
  initialDoc = null,
}) => {
  const [currentDoc, setCurrentDoc] = useState<DocTab | null>(initialDoc);

  const handleBackClick = () => {
    if (currentDoc !== null) {
      setCurrentDoc(null);
    } else {
      onBack();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex flex-col w-screen h-screen bg-white dark:bg-black text-zinc-900 dark:text-zinc-100 overflow-hidden font-sans">
      {/* Top Header Bar */}
      <header className="h-16 px-4 sm:px-6 border-b border-zinc-200 dark:border-white/10 bg-zinc-50/90 dark:bg-zinc-950/80 backdrop-blur-md flex items-center justify-between z-20 shrink-0">
        <div className="flex items-center gap-3.5">
          <button
            type="button"
            onClick={handleBackClick}
            className="flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-medium text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white hover:bg-zinc-200 dark:hover:bg-white/10 transition-colors border border-zinc-300 dark:border-white/10 cursor-pointer"
            title={currentDoc !== null ? "Back to Documents" : "Close Documents & Back to Chat"}
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="hidden sm:inline">{currentDoc !== null ? "Back" : "Back to Chat"}</span>
          </button>
          
          <div className="flex items-center gap-2.5">
            <AestificLogo className="w-5 h-5 text-black dark:text-white" />
            <span className="font-bold text-sm sm:text-base tracking-tight text-zinc-900 dark:text-white">
              Aestific Platform
            </span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {onAccept && !isAccepted && currentDoc === 'terms' && (
            <button
              type="button"
              onClick={onAccept}
              className="px-4 sm:px-5 py-2 rounded-xl text-xs font-semibold bg-black text-white hover:bg-zinc-800 dark:bg-white dark:text-black dark:hover:bg-zinc-200 shadow-sm transition-all flex items-center gap-2 active:scale-95 cursor-pointer"
            >
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>Accept Terms</span>
            </button>
          )}

          {isAccepted && currentDoc === 'terms' && (
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>Terms Accepted</span>
            </span>
          )}
        </div>
      </header>

      {/* Main Content Area */}
      <div className="flex-1 overflow-y-auto px-4 sm:px-8 py-6 sm:py-8 relative">
        <div className="max-w-4xl mx-auto space-y-6 relative z-10">
          {/* Unified Document Content Presentation */}
          <DocumentsView
            currentDoc={currentDoc}
            onDocChange={setCurrentDoc}
            showHeader={currentDoc === null}
          />

          {/* Bottom Acceptance Box when viewing terms */}
          {onAccept && !isAccepted && currentDoc === 'terms' && (
            <div className="mt-8 pt-6 border-t border-zinc-200 dark:border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4 bg-zinc-100 dark:bg-zinc-900 rounded-2xl p-5 border border-zinc-300 dark:border-white/10">
              <div>
                <p className="text-sm font-semibold text-zinc-900 dark:text-white">Ready to proceed?</p>
                <p className="text-xs text-zinc-600 dark:text-zinc-400 mt-0.5">
                  Click accept below to acknowledge these terms and access Aestific AI.
                </p>
              </div>
              <button
                type="button"
                onClick={onAccept}
                className="w-full sm:w-auto px-6 py-3 rounded-xl text-xs sm:text-sm font-semibold bg-black text-white hover:bg-zinc-800 dark:bg-white dark:text-black dark:hover:bg-zinc-200 shadow-sm transition-all flex items-center justify-center gap-2 active:scale-95 cursor-pointer shrink-0"
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>Accept all of it</span>
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
